### ISSUE TITLE
Keep Streaming when closing ingame window.

### ISSUE THREAD

**Issue by Lucaspec72** [jrodrigv/OfCourseIStillLoveYou#10]
The streaming stops as soon as the camera window is closed, and it can't be minimised or hidden, so it kinds of defeats the point of the mod imo. would it be possible to keep streaming when the camera window is closed ?

**Comment by jrodrigv** [comment]
Hi @Lucaspec72 , there is a way to hide the OCISLY UI but maybe it is not very obvious. 
Just  by clicking the OCISLY mod icon (the mod icon located on the right bar) will hide automatically all the OCISLY windows but will keep the camera streaming active.

Let me know if this works for you.

**Comment by Lucaspec72** [comment]
Thank you for the quick reply !
