### ISSUE TITLE
Loss of signal when pausing game with Esc or TimeControl

### ISSUE THREAD

**Issue by EritoKaio** [jrodrigv/OfCourseIStillLoveYou#3]
Is there a way to keep the cameras streaming even when the game is paused or is it a limitation?
I was trying to do camera handovers for different scenes and noticed they lose signal when the game is paused, meaning client loses track of what cameras they had set. 
(there's no way my PC can handle more than 2 cameras at once even on my 1700X+RTX2070)
![ocisly_losssignal](https://user-images.githubusercontent.com/26747759/115934598-4c268600-a489-11eb-9552-eb7efe92ac3a.png)

**Comment by jrodrigv** [comment]
When the game is paused there is no streaming happening and after 1 second without receiving any feed, the camera data is deleted because it assumes something went wrong.

**Comment by EritoKaio** [comment]
Is that the game stopping the streaming or is it just how its coded? Is there a way around it for a future update (no rush :P)?
I ask because Waterfall plumes' effects keep running even with the game paused.

**Comment by jrodrigv** [comment]
I think is game itself, the mod is implemented to never stop streaming unless you press the streaming button or there is no vessel or camera after going RUD. I think the waterfall effects are just an animation and particles.

**Comment by EritoKaio** [comment]
Ah, gotcha. Ill figure out another way to record without having to do multiple takes. I was hoping running the main game in lower res would increase the overall framerate but didn't, I think I'm just CPU bottlenecked.
Thank you! This mod is great.

**Comment by jrodrigv** [comment]
BTW are you using the release  v1.0.98 ? I have improved quite a lot the performance in that version.

**Comment by EritoKaio** [comment]
Yep, I did notice a small improvement, but its just the amount of stuff I have going on I'm pretty sure. Combined with rendering another 3-4 cameras it drops my game to 10fps. I'll just see if I can speed it up a little  after recording without making it look weird. I'll be happy enough if I can keep this shot in the video haha
![1qb1bc1a_31bc1](https://user-images.githubusercontent.com/26747759/115964640-5c884080-a51d-11eb-87c2-593c6957f4c4.gif)

**Comment by jrodrigv** [comment]
Yes, I understand. To be honest the same happens to me when I try do my crazy thing with RO  https://youtu.be/Y_JzKbNrnvw?t=283  The video has been speed up x2 I was getting 10 FPS

**Comment by EritoKaio** [comment]
Yeah haha, hopefully the devs can improve the game's performance in KSP2 so we can do all the crazy stuff, honestly my nº1 wish for it :P

**Comment by EritoKaio** [comment]
Actually found a good enough workaround. Using TimeControl I can set the game to super-slow motion, slow enough that im pretty much not moving, but fast enough for the game to give a "frame" often enough for the cameras to not go offline.
![image](https://user-images.githubusercontent.com/26747759/115973829-dcc79980-a54f-11eb-9025-734693129eea.png)

**Comment by jrodrigv** [comment]
@EritoKaio Would you mind testing the lastest release?  I have implemented a fix to recover automatically the streaming after un pausing the game

**Comment by EritoKaio** [comment]
YEP! Seems to recover on the right window now! Thank you :D 
![1wS1d2ca_c1d2c](https://user-images.githubusercontent.com/26747759/117888440-fd128a80-b2a9-11eb-83cf-e4d9b504f63d.gif)

**Comment by jrodrigv** [comment]
Nice!
