### ISSUE TITLE
DLL not compatible 

### ISSUE THREAD

**Issue by CollatRL** [jrodrigv/OfCourseIStillLoveYou#7]
When opening ksp 1.11.2 following all instructions listed and using any version of the mod, the game gets stuck on loading expansion breaking ground/serenity and I get a "DLL not compatible with current game version" error and the game fails to open. I even used an instance of the game that this worked on previously and got the same error.

**Comment by jrodrigv** [comment]
I would need you KSP.log file for troubleshooting

**Comment by CollatRL** [comment]
[KSP.log](https://github.com/jrodrigv/OfCourseIStillLoveYou/files/7096038/KSP.log)

**Comment by jrodrigv** [comment]
I'm afraid that after investigation I can't reproduce your issue.  I suggest to try with a minimal set of mods (OCISLY + dependencies) . Besides I suggest to try an old version of module manager like 4.1.4 version

**Comment by CollatRL** [comment]
Awesome, thanks. That ended up working and I managed to fix the issue.
